import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { BillablePlan, Invoice, InvoiceStatus, PaymentMethod } from './types';

export const invoiceStatusLabels:Record<InvoiceStatus,string>={issued:'Emitido',partially_paid:'Pago parcial',paid:'Pagado',cancelled:'Anulado'};
export const paymentMethodLabels:Record<PaymentMethod,string>={cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'};
const money=(value:string)=>new Intl.NumberFormat('es-PY',{style:'currency',currency:'PYG',maximumFractionDigits:0}).format(Number(value));

export function Billing({patientId}:{patientId:string}){
  const [invoices,setInvoices]=useState<Invoice[]>([]);const [plans,setPlans]=useState<BillablePlan[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.invoices(patientId),api.billablePlans(patientId)]).then(([i,p])=>{setInvoices(i);setPlans(p);}).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar la facturación.'));
  useEffect(()=>{load();},[patientId]);
  async function issue(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{await api.createInvoice(patientId,String(data.get('treatment_plan_id')),String(data.get('due_date'))||null);form.reset();await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible emitir el comprobante.');}finally{setBusy(false);}}
  async function pay(event:FormEvent<HTMLFormElement>,invoiceId:string){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const updated=await api.addPayment(patientId,invoiceId,{amount:String(data.get('amount')),method:String(data.get('method')) as PaymentMethod,paid_at:new Date(String(data.get('paid_at'))).toISOString(),reference:String(data.get('reference')).trim()||null});setInvoices((items)=>items.map((item)=>item.id===updated.id?updated:item));form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible registrar el pago.');}finally{setBusy(false);}}
  async function cancel(invoiceId:string){setBusy(true);setError('');try{const updated=await api.cancelInvoice(patientId,invoiceId);setInvoices((items)=>items.map((item)=>item.id===updated.id?updated:item));}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible anular el comprobante.');}finally{setBusy(false);}}
  return <section className="card" aria-labelledby="billing-title"><h2 id="billing-title">Facturación interna y pagos</h2><p>Registro administrativo interno. No corresponde a facturación electrónica tributaria.</p>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <form className="form-grid" onSubmit={issue}><h3>Emitir desde un plan aceptado</h3><label>Plan de tratamiento<select name="treatment_plan_id" required defaultValue=""><option value="" disabled>Seleccione</option>{plans.map((plan)=><option key={plan.id} value={plan.id}>{plan.title} — {money(plan.total)}</option>)}</select></label><label>Vencimiento<input name="due_date" type="date"/></label><button disabled={busy||!plans.length}>Emitir comprobante interno</button>{!plans.length&&<p className="hint">No hay planes aceptados pendientes de emisión.</p>}</form>
    {invoices.length?invoices.map((invoice)=><article className="clinical-entry" key={invoice.id}><h3>{invoice.number} · {invoice.description}</h3><p><strong>{invoiceStatusLabels[invoice.status]}</strong> · Total {money(invoice.amount)} · Pagado {money(invoice.paid_amount)} · Saldo {money(invoice.balance)}</p>{invoice.due_date&&<p>Vencimiento: {new Intl.DateTimeFormat('es-PY').format(new Date(`${invoice.due_date}T12:00:00`))}</p>}
      {invoice.payments.length?<ul>{invoice.payments.map((payment)=><li key={payment.id}>{new Intl.DateTimeFormat('es-PY',{dateStyle:'medium'}).format(new Date(payment.paid_at))}: {money(payment.amount)} · {paymentMethodLabels[payment.method]}{payment.reference?` · ${payment.reference}`:''}</li>)}</ul>:<p>Sin pagos registrados.</p>}
      {!['paid','cancelled'].includes(invoice.status)&&<form className="form-grid" onSubmit={(event)=>pay(event,invoice.id)}><h4>Registrar pago</h4><label>Importe<input name="amount" type="number" min="1" max={invoice.balance} step="1" required/></label><label>Medio<select name="method" defaultValue="cash">{Object.entries(paymentMethodLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Fecha y hora<input name="paid_at" type="datetime-local" required/></label><label>Referencia<input name="reference" maxLength={120}/></label><button disabled={busy}>Registrar pago</button>{invoice.status==='issued'&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>cancel(invoice.id)}>Anular comprobante</button>}</form>}
    </article>):<p>No hay comprobantes emitidos.</p>}
  </section>;
}
