import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { NotificationChannel, NotificationConsent, NotificationDeliveryStatus, PatientNotification } from './types';

export const channelLabels:Record<NotificationChannel,string>={whatsapp:'WhatsApp',sms:'SMS'};
export const deliveryStatusLabels:Record<NotificationDeliveryStatus,string>={pending:'Pendiente',sent:'Enviado',failed:'Fallido',cancelled:'Cancelado'};

export function Notifications({patientId}:{patientId:string}){
  const [consents,setConsents]=useState<NotificationConsent[]>([]);const [items,setItems]=useState<PatientNotification[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.notificationConsents(patientId),api.notifications(patientId)]).then(([c,n])=>{setConsents(c);setItems(n);}).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar las notificaciones.'));
  useEffect(()=>{load();},[patientId]);
  const active=(channel:NotificationChannel)=>consents.some((item)=>item.channel===channel&&item.status==='granted');
  async function grant(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{await api.grantNotificationConsent(patientId,String(data.get('channel')) as NotificationChannel,new Date(String(data.get('granted_at'))).toISOString(),String(data.get('evidence_location')).trim());form.reset();await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible registrar la autorización.');}finally{setBusy(false);}}
  async function revoke(channel:NotificationChannel){setBusy(true);setError('');try{await api.revokeNotificationConsent(patientId,channel);await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible revocar la autorización.');}finally{setBusy(false);}}
  async function queue(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const item=await api.createNotification(patientId,String(data.get('channel')) as NotificationChannel,String(data.get('message')).trim());setItems((current)=>[item,...current]);form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible preparar la notificación.');}finally{setBusy(false);}}
  async function cancel(id:string){setBusy(true);setError('');try{const updated=await api.cancelNotification(patientId,id);setItems((current)=>current.map((item)=>item.id===id?updated:item));}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cancelar la notificación.');}finally{setBusy(false);}}
  return <section className="card" aria-labelledby="notifications-title"><h2 id="notifications-title">Notificaciones por WhatsApp o SMS</h2><p>Antes de preparar un mensaje debe existir autorización documentada para ese canal. Evite incluir diagnósticos o información clínica sensible.</p>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <form className="form-grid" onSubmit={grant}><h3>Registrar autorización</h3><label>Canal<select name="channel"><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></select></label><label>Fecha y hora de autorización<input name="granted_at" type="datetime-local" required/></label><label>Ubicación del documento firmado<input name="evidence_location" maxLength={240} placeholder="Archivo físico / referencia" required/></label><button disabled={busy}>Registrar autorización</button></form>
    <div className="actions" aria-label="Autorizaciones vigentes">{(['whatsapp','sms'] as NotificationChannel[]).map((channel)=><div key={channel}><strong>{channelLabels[channel]}:</strong> {active(channel)?'Autorizado':'No autorizado'} {active(channel)&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>revoke(channel)}>Revocar</button>}</div>)}</div>
    <form className="form-grid" onSubmit={queue}><h3>Preparar mensaje</h3><label>Canal<select name="channel" defaultValue={active('whatsapp')?'whatsapp':active('sms')?'sms':''}><option value="" disabled>Seleccione un canal autorizado</option><option value="whatsapp" disabled={!active('whatsapp')}>WhatsApp</option><option value="sms" disabled={!active('sms')}>SMS</option></select></label><label>Mensaje<textarea name="message" maxLength={320} placeholder="Le recordamos su cita en Dar Sonrisas…" required/></label><button disabled={busy||(!active('whatsapp')&&!active('sms'))}>Agregar a la cola</button></form>
    <h3>Historial de envíos</h3>{items.length?items.map((item)=><article className="clinical-entry" key={item.id}><strong>{channelLabels[item.channel]} · {deliveryStatusLabels[item.status]}</strong><p>{item.message}</p><small>{item.recipient} · {new Intl.DateTimeFormat('es-PY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at))}</small>{item.status==='pending'&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>cancel(item.id)}>Cancelar pendiente</button>}</article>):<p>No hay notificaciones registradas.</p>}
  </section>;
}
