import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api, ApiError } from './api';
import type { DentalCondition, OdontogramEvent, ToothSurface, Treatment } from './types';

const permanent=['18','17','16','15','14','13','12','11','21','22','23','24','25','26','27','28','48','47','46','45','44','43','42','41','31','32','33','34','35','36','37','38'];
const conditions:Record<DentalCondition,string>={healthy:'Sano',caries:'Caries',missing:'Ausente',restoration:'Restauración',crown:'Corona',implant:'Implante',root_canal:'Endodoncia',extraction_indicated:'Extracción indicada'};
const surfaces:Record<ToothSurface,string>={whole:'Pieza completa',mesial:'Mesial',distal:'Distal',buccal:'Vestibular',lingual:'Lingual/palatina',occlusal:'Oclusal',incisal:'Incisal'};

export function Odontogram({patientId}:{patientId:string}){
  const [current,setCurrent]=useState<OdontogramEvent[]>([]);const [history,setHistory]=useState<OdontogramEvent[]>([]);const [treatments,setTreatments]=useState<Treatment[]>([]);const [tooth,setTooth]=useState('11');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.odontogramCurrent(patientId),api.odontogramHistory(patientId),api.treatments()]).then(([c,h,t])=>{setCurrent(c);setHistory(h);setTreatments(t);}).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar el odontograma.'));
  useEffect(()=>{load();},[patientId]);
  const toothState=useMemo(()=>{const state=new Map<string,DentalCondition>();for(const item of current){if(!state.has(item.tooth_code))state.set(item.tooth_code,item.condition);}return state;},[current]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{await api.recordOdontogramEvent(patientId,{tooth_code:tooth,surface:String(data.get('surface')) as ToothSurface,condition:String(data.get('condition')) as DentalCondition,observed_at:new Date().toISOString(),note:String(data.get('note')).trim()||null,treatment_id:String(data.get('treatment_id'))||null});await load();form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible registrar el estado.');}finally{setBusy(false);}}
  return <section className="card odontogram" aria-labelledby="odontogram-title"><h2 id="odontogram-title">Odontograma</h2><p>Seleccione una pieza mediante numeración FDI. Los colores se acompañan siempre con texto.</p>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <div className="teeth-grid" role="group" aria-label="Dentición permanente">{permanent.map((code)=><button type="button" key={code} aria-pressed={tooth===code} className={`tooth tooth--${toothState.get(code)||'unrecorded'}`} onClick={()=>setTooth(code)}><strong>{code}</strong><span>{toothState.has(code)?conditions[toothState.get(code)!]:'Sin registro'}</span></button>)}</div>
    <form className="form-grid" onSubmit={submit}><h3>Registrar hallazgo o resultado en pieza {tooth}</h3><label>Superficie<select name="surface" defaultValue="whole">{Object.entries(surfaces).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Estado<select name="condition" defaultValue="healthy">{Object.entries(conditions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Tratamiento relacionado<select name="treatment_id" defaultValue=""><option value="">Ninguno</option>{treatments.map((item)=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></label><label>Nota<textarea name="note" maxLength={2000}/></label><button disabled={busy}>{busy?'Registrando…':'Registrar sin sobrescribir historial'}</button></form>
    <details><summary>Historial del odontograma ({history.length})</summary>{history.map((item)=><article className="clinical-entry" key={item.id}><strong>Pieza {item.tooth_code} · {surfaces[item.surface]} · {conditions[item.condition]}</strong><p>{item.note||'Sin nota'}</p><small>{new Intl.DateTimeFormat('es-PY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.observed_at))}</small></article>)}</details>
  </section>;
}
