import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { AuthenticatedUser, ClinicalHistoryDocument, ConsentRecord, Patient, PatientUpdate } from './types';
import { Odontogram } from './Odontogram';
import { TreatmentPlans } from './TreatmentPlans';
import { Evolution } from './Evolution';
import { Billing } from './Billing';
import { Notifications } from './Notifications';
import { selectedSignedDocument, validateSignedDocument } from './signedDocument';

const consentStatusLabels:Record<ConsentRecord['status'],string>={active:'Activo',revoked:'Revocado'};
type Section='profile'|'odontogram'|'plans'|'evolution'|'billing'|'notifications'|'consents';

export function PatientDetail({patient,user,onBack,onUpdate}:{patient:Patient;user:AuthenticatedUser;onBack:()=>void;onUpdate:(id:string,input:PatientUpdate)=>Promise<void>}){
  const clinicalAccess=user.roles.some((role)=>role==='admin'||role==='profesional');
  const financialAccess=user.roles.some((role)=>role==='admin'||role==='recepcion');
  const administrativeAccess=user.roles.some((role)=>role==='admin'||role==='recepcion');
  const [section,setSection]=useState<Section>('profile');
  const [historyDocuments,setHistoryDocuments]=useState<ClinicalHistoryDocument[]>([]);const [consents,setConsents]=useState<ConsentRecord[]>([]);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{setError('');const requests:Promise<unknown>[]=[api.consents(patient.id).then(setConsents)];if(clinicalAccess){requests.push(api.clinicalHistoryDocuments(patient.id).then(setHistoryDocuments));}Promise.all(requests).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar el expediente.'));},[patient.id,clinicalAccess]);
  async function uploadHistory(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;try{const input=form.elements.namedItem('attachment') as HTMLInputElement;const document=await api.uploadClinicalHistoryDocument(patient.id,validateSignedDocument(input.files?.[0]??null));setHistoryDocuments((items)=>[document,...items]);form.reset();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible adjuntar el historial clínico.');}finally{setBusy(false);}}
  async function downloadHistory(document:ClinicalHistoryDocument){setError('');try{await api.downloadClinicalHistoryDocument(patient.id,document.id,document.attachment_filename);}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible descargar el historial clínico.');}}
  async function addConsent(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const attachment=selectedSignedDocument(data);const item=await api.createConsentWithAttachment(patient.id,{consent_type:String(data.get('consent_type')).trim(),document_version:String(data.get('document_version')).trim(),purpose:String(data.get('purpose')).trim(),signed_at:new Date(String(data.get('signed_at'))).toISOString(),signer_name:String(data.get('signer_name')).trim(),signer_relationship:String(data.get('signer_relationship')).trim()||null,evidence_location:String(data.get('evidence_location')).trim()||null},attachment);setConsents((items)=>[item,...items]);form.reset();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible guardar.');}finally{setBusy(false);}}
  async function attachConsent(event:FormEvent<HTMLFormElement>,consentId:string){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;try{const updated=await api.attachConsentDocument(patient.id,consentId,selectedSignedDocument(new FormData(form)));setConsents((items)=>items.map((item)=>item.id===consentId?updated:item));form.reset();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible adjuntar el documento.');}finally{setBusy(false);}}
  async function downloadConsent(item:ConsentRecord){setError('');try{await api.downloadConsentDocument(patient.id,item.id,item.attachment_filename!);}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible descargar el documento.');}}
  async function savePatient(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);const input:PatientUpdate={first_name:String(data.get('first_name')).trim(),last_name:String(data.get('last_name')).trim(),birth_date:String(data.get('birth_date'))||null,email:String(data.get('email')).trim()||null,phone:String(data.get('phone')).trim()||null,address:String(data.get('address')).trim()||null,city:String(data.get('city')).trim()||null,occupation:String(data.get('occupation')).trim()||null,emergency_contact_name:String(data.get('emergency_contact_name')).trim()||null,emergency_contact_phone:String(data.get('emergency_contact_phone')).trim()||null,active:data.get('active')==='true'};try{await onUpdate(patient.id,input);}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible actualizar el paciente.');}finally{setBusy(false);}}
  const tabs:{id:Section;label:string;visible:boolean}[]=[{id:'profile',label:'Perfil',visible:true},{id:'odontogram',label:'Odontograma',visible:clinicalAccess},{id:'plans',label:'Planes',visible:clinicalAccess},{id:'evolution',label:'Evolución',visible:clinicalAccess},{id:'billing',label:'Facturación',visible:financialAccess},{id:'notifications',label:'Notificaciones',visible:financialAccess},{id:'consents',label:'Consentimientos',visible:true}];
  return <section aria-labelledby="patient-detail-title"><button className="button-secondary" onClick={onBack}>← Volver a pacientes</button><div className="section-heading"><div><p className="eyebrow">Expediente del paciente</p><h1 id="patient-detail-title">{patient.first_name} {patient.last_name}</h1></div><span>{patient.document_type} {patient.document_number}</span></div>
    {error&&<div className="notice notice--error" role="alert">{error}</div>}<div className="module-tabs" role="tablist" aria-label="Módulos del expediente">{tabs.filter((tab)=>tab.visible).map((tab)=><button type="button" role="tab" aria-selected={section===tab.id} aria-controls={`panel-${tab.id}`} key={tab.id} onClick={()=>setSection(tab.id)}>{tab.label}</button>)}</div>
    <div className="module-panel" id={`panel-${section}`} role="tabpanel">
      {section==='profile'&&<><section className="card" aria-labelledby="personal-title"><h2 id="personal-title">Perfil personal</h2><dl className="detail-grid"><div><dt>Nacimiento</dt><dd>{patient.birth_date||'No informado'}</dd></div><div><dt>Teléfono</dt><dd>{patient.phone||'No informado'}</dd></div><div><dt>Correo</dt><dd>{patient.email||'No informado'}</dd></div><div><dt>Dirección</dt><dd>{[patient.address,patient.city].filter(Boolean).join(', ')||'No informada'}</dd></div><div><dt>Ocupación</dt><dd>{patient.occupation||'No informada'}</dd></div><div><dt>Contacto de emergencia</dt><dd>{[patient.emergency_contact_name,patient.emergency_contact_phone].filter(Boolean).join(' · ')||'No informado'}</dd></div><div><dt>Estado</dt><dd>{patient.active?'Activo':'Inactivo'}</dd></div></dl></section>{administrativeAccess&&<form className="card form-grid" onSubmit={savePatient}><h2>Editar datos del paciente</h2><label>Nombre<input name="first_name" defaultValue={patient.first_name} required/></label><label>Apellido<input name="last_name" defaultValue={patient.last_name} required/></label><label>Nacimiento<input name="birth_date" type="date" defaultValue={patient.birth_date||''}/></label><label>Correo<input name="email" type="email" defaultValue={patient.email||''}/></label><label>Teléfono<input name="phone" defaultValue={patient.phone||''}/></label><label>Dirección<input name="address" defaultValue={patient.address||''}/></label><label>Ciudad<input name="city" defaultValue={patient.city||''}/></label><label>Ocupación<input name="occupation" defaultValue={patient.occupation||''}/></label><label>Contacto de emergencia<input name="emergency_contact_name" defaultValue={patient.emergency_contact_name||''}/></label><label>Teléfono de emergencia<input name="emergency_contact_phone" defaultValue={patient.emergency_contact_phone||''}/></label><label>Estado<select name="active" defaultValue={String(patient.active)}><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button disabled={busy}>Guardar datos</button></form>}{clinicalAccess&&<section className="card" aria-labelledby="history-title"><h2 id="history-title">Historial clínico</h2><p>Adjuntá el documento físico firmado por el paciente.</p><form className="attachment-form" onSubmit={uploadHistory}><label>Documento firmado (PDF, JPG o PNG; máximo 10 MB)<input name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" required/></label><button disabled={busy}>Adjuntar historial clínico</button></form>{historyDocuments.length>0&&<div className="clinical-entry"><p>Documento adjunto: {historyDocuments[0].attachment_filename}</p><button type="button" className="button-secondary" onClick={()=>void downloadHistory(historyDocuments[0])}>Descargar historial clínico</button></div>}</section>}</>}
      {section==='odontogram'&&clinicalAccess&&<Odontogram patientId={patient.id}/>}
      {section==='plans'&&clinicalAccess&&<TreatmentPlans patientId={patient.id}/>}
      {section==='evolution'&&clinicalAccess&&<Evolution patientId={patient.id}/>}
      {section==='billing'&&financialAccess&&<Billing patientId={patient.id}/>}
      {section==='notifications'&&financialAccess&&<Notifications patientId={patient.id}/>}
      {section==='consents'&&<><form className="card form-grid" onSubmit={addConsent}><h2>Registrar consentimiento firmado</h2><label>Tipo<input name="consent_type" defaultValue="consentimiento informado" required/></label><label>Versión del documento<input name="document_version" placeholder="v1.0" required/></label><label>Finalidad<input name="purpose" required/></label><label>Fecha y hora de firma<input name="signed_at" type="datetime-local" required/></label><label>Firmante<input name="signer_name" required/></label><label>Relación con el paciente<input name="signer_relationship" placeholder="Paciente, madre, tutor…"/></label><label>Ubicación del original físico (opcional)<input name="evidence_location" placeholder="Archivo físico / carpeta / referencia"/></label><label>Adjuntar documento firmado (PDF, JPG o PNG; máximo 10 MB)<input name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" required/></label><button disabled={busy}>Guardar consentimiento y adjunto</button></form><section className="card"><h2>Consentimientos</h2>{consents.length?consents.map((item)=><article className="clinical-entry" key={item.id}><strong>{item.consent_type} · {item.document_version}</strong><p>{item.purpose}</p><small>{item.signer_name} · {consentStatusLabels[item.status]}{item.evidence_location?` · Original: ${item.evidence_location}`:''}</small>{item.attachment_filename?<div className="actions"><button type="button" className="button-secondary" onClick={()=>void downloadConsent(item)}>Descargar {item.attachment_filename}</button></div>:<form className="attachment-form" onSubmit={(event)=>void attachConsent(event,item.id)}><label>Adjuntar documento firmado<input name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" required/></label><button disabled={busy}>Adjuntar documento</button></form>}</article>):<p>No hay consentimientos registrados.</p>}</section></>}
    </div>
  </section>;
}
