import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { AuthenticatedUser, ClinicalEntry, ClinicalProfile, ConsentRecord, Patient } from './types';
import { Odontogram } from './Odontogram';
import { TreatmentPlans } from './TreatmentPlans';
import { Billing } from './Billing';
import { Notifications } from './Notifications';

const splitList = (value: FormDataEntryValue | null) => String(value ?? '').split(',').map((item)=>item.trim()).filter(Boolean);
export const clinicalEntryLabels:Record<ClinicalEntry['entry_type'],string>={consultation:'Consulta',evolution:'Evolución',diagnosis:'Diagnóstico',procedure:'Procedimiento'};
const consentStatusLabels:Record<ConsentRecord['status'],string>={active:'Activo',revoked:'Revocado'};

export function PatientDetail({patient,user,onBack}:{patient:Patient;user:AuthenticatedUser;onBack:()=>void}) {
  const clinicalAccess=user.roles.some((role)=>role==='admin'||role==='profesional');
  const financialAccess=user.roles.some((role)=>role==='admin'||role==='recepcion');
  const [profile,setProfile]=useState<ClinicalProfile|null>(null); const [entries,setEntries]=useState<ClinicalEntry[]>([]); const [consents,setConsents]=useState<ConsentRecord[]>([]);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{setError('');const requests:Promise<unknown>[]=[api.consents(patient.id).then(setConsents)];if(clinicalAccess){requests.push(api.clinicalProfile(patient.id).then(setProfile),api.clinicalEntries(patient.id).then(setEntries));}Promise.all(requests).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar el expediente.'));},[patient.id,clinicalAccess]);
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{setProfile(await api.saveClinicalProfile(patient.id,{blood_type:String(data.get('blood_type')).trim()||null,allergies:splitList(data.get('allergies')),medications:splitList(data.get('medications')),medical_conditions:splitList(data.get('medical_conditions')),observations:String(data.get('observations')).trim()||null}));}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible guardar.');}finally{setBusy(false);}}
  async function addEntry(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const entry=await api.createClinicalEntry(patient.id,{entry_type:String(data.get('entry_type')) as ClinicalEntry['entry_type'],occurred_at:new Date(String(data.get('occurred_at'))).toISOString(),summary:String(data.get('summary')).trim(),notes:String(data.get('notes')).trim()});setEntries((items)=>[entry,...items]);form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible guardar.');}finally{setBusy(false);}}
  async function addConsent(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const item=await api.createConsent(patient.id,{consent_type:String(data.get('consent_type')).trim(),document_version:String(data.get('document_version')).trim(),purpose:String(data.get('purpose')).trim(),signed_at:new Date(String(data.get('signed_at'))).toISOString(),signer_name:String(data.get('signer_name')).trim(),signer_relationship:String(data.get('signer_relationship')).trim()||null,evidence_location:String(data.get('evidence_location')).trim()});setConsents((items)=>[item,...items]);form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible guardar.');}finally{setBusy(false);}}
  return <section aria-labelledby="patient-detail-title"><button className="button-secondary" onClick={onBack}>← Volver a pacientes</button><div className="section-heading"><div><p className="eyebrow">Expediente del paciente</p><h1 id="patient-detail-title">{patient.first_name} {patient.last_name}</h1></div><span>{patient.document_type} {patient.document_number}</span></div>
    {error&&<div className="notice notice--error" role="alert">{error}</div>}
    <section className="card" aria-labelledby="personal-title"><h2 id="personal-title">Perfil personal</h2><dl className="detail-grid"><div><dt>Nacimiento</dt><dd>{patient.birth_date||'No informado'}</dd></div><div><dt>Teléfono</dt><dd>{patient.phone||'No informado'}</dd></div><div><dt>Correo</dt><dd>{patient.email||'No informado'}</dd></div><div><dt>Dirección</dt><dd>{[patient.address,patient.city].filter(Boolean).join(', ')||'No informada'}</dd></div><div><dt>Ocupación</dt><dd>{patient.occupation||'No informada'}</dd></div><div><dt>Contacto de emergencia</dt><dd>{[patient.emergency_contact_name,patient.emergency_contact_phone].filter(Boolean).join(' · ')||'No informado'}</dd></div></dl></section>
    {clinicalAccess&&<><form className="card form-grid" onSubmit={saveProfile}><h2>Antecedentes médicos</h2><label>Grupo sanguíneo<input name="blood_type" defaultValue={profile?.blood_type||''} maxLength={10}/></label><label>Alergias, separadas por comas<input name="allergies" defaultValue={profile?.allergies.join(', ')||''}/></label><label>Medicamentos, separados por comas<input name="medications" defaultValue={profile?.medications.join(', ')||''}/></label><label>Condiciones médicas, separadas por comas<input name="medical_conditions" defaultValue={profile?.medical_conditions.join(', ')||''}/></label><label>Observaciones<textarea name="observations" defaultValue={profile?.observations||''} maxLength={4000}/></label><button disabled={busy}>Guardar antecedentes</button></form>
    <form className="card form-grid" onSubmit={addEntry}><h2>Nueva entrada clínica</h2><label>Tipo<select name="entry_type"><option value="consultation">Consulta</option><option value="evolution">Evolución</option><option value="diagnosis">Diagnóstico</option><option value="procedure">Procedimiento</option></select></label><label>Fecha y hora<input name="occurred_at" type="datetime-local" required/></label><label>Resumen<input name="summary" maxLength={240} required/></label><label>Notas clínicas<textarea name="notes" maxLength={12000} required/></label><button disabled={busy}>Agregar a la historia</button></form>
    <Odontogram patientId={patient.id}/><TreatmentPlans patientId={patient.id}/><section className="card"><h2>Historia clínica</h2>{entries.length?entries.map((entry)=><article className="clinical-entry" key={entry.id}><time dateTime={entry.occurred_at}>{new Intl.DateTimeFormat('es-PY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(entry.occurred_at))}</time><h3>{entry.summary}</h3><p>{entry.notes}</p><small>{clinicalEntryLabels[entry.entry_type]}</small></article>):<p>No hay entradas clínicas.</p>}</section></>}
    {financialAccess&&<><Billing patientId={patient.id}/><Notifications patientId={patient.id}/></>}<form className="card form-grid" onSubmit={addConsent}><h2>Registrar consentimiento firmado</h2><label>Tipo<input name="consent_type" defaultValue="consentimiento informado" required/></label><label>Versión del documento<input name="document_version" placeholder="v1.0" required/></label><label>Finalidad<input name="purpose" required/></label><label>Fecha y hora de firma<input name="signed_at" type="datetime-local" required/></label><label>Firmante<input name="signer_name" required/></label><label>Relación con el paciente<input name="signer_relationship" placeholder="Paciente, madre, tutor…"/></label><label>Ubicación segura del original<input name="evidence_location" placeholder="Archivo físico / carpeta / referencia" required/></label><button disabled={busy}>Registrar evidencia</button></form>
    <section className="card"><h2>Consentimientos</h2>{consents.length?consents.map((item)=><article className="clinical-entry" key={item.id}><strong>{item.consent_type} · {item.document_version}</strong><p>{item.purpose}</p><small>{item.signer_name} · {consentStatusLabels[item.status]} · {item.evidence_location}</small></article>):<p>No hay consentimientos registrados.</p>}</section>
  </section>;
}
