import { FormEvent, useState } from 'react';

type PublicView='home'|'contact';
const whatsappUrl='https://wa.me/595994761736?text=Hola%20Dar%20Sonrisas%2C%20quisiera%20realizar%20una%20consulta.';
const facebookUrl='https://www.instagram.com/reel/DVroxG8jRWn/?stkn=eHR4ZW42YWt1cmQ=';
const instagramUrl='https://www.instagram.com/odonto_darsonrisas?stkn=MXd5aXM1Zzgwbzd2eA==';

export function buildContactMailto(data:{name:string;email:string;phone:string;subject:string;message:string}){
  const subject=encodeURIComponent(`Consulta web: ${data.subject}`);
  const body=encodeURIComponent(`Nombre: ${data.name}\nCorreo: ${data.email}\nTeléfono: ${data.phone||'No informado'}\n\nConsulta:\n${data.message}`);
  return `mailto:mendez.jose87@gmail.com?subject=${subject}&body=${body}`;
}

export function PublicSite({onStaffAccess}:{onStaffAccess:()=>void}){
  const [view,setView]=useState<PublicView>('home');
  const [showVideo,setShowVideo]=useState(false);
  const go=(next:PublicView)=>{setView(next);window.scrollTo({top:0,behavior:'smooth'});};
  function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);window.location.href=buildContactMailto({name:String(data.get('name')).trim(),email:String(data.get('email')).trim(),phone:String(data.get('phone')).trim(),subject:String(data.get('subject')).trim(),message:String(data.get('message')).trim()});}
  return <div className="public-site"><a className="skip-link" href="#contenido-publico">Saltar al contenido</a><header className="public-header"><button type="button" className="logo-button" onClick={()=>go('home')} aria-label="Ir al inicio"><img src="/media/dar-sonrisas-logo.png" alt="Dar Sonrisas Odontología Integral"/></button><nav aria-label="Navegación pública"><button type="button" onClick={()=>go('home')}>Inicio</button><button type="button" onClick={()=>{go('home');setTimeout(()=>document.getElementById('nosotros')?.scrollIntoView({behavior:'smooth'}),0);}}>Nosotros</button><button type="button" onClick={()=>go('contact')}>Contacto</button></nav><div className="header-actions"><a className="pill pill--whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Consultar por WhatsApp">WhatsApp</a><button type="button" className="pill pill--staff" onClick={onStaffAccess}>Acceso personal</button></div></header>
    {view==='home'?<main id="contenido-publico"><section className="hero" aria-labelledby="hero-title">{showVideo&&<video autoPlay muted loop playsInline poster="/media/clinic-hero.png" aria-hidden="true"><source src="/media/clinic-hero.mp4" type="video/mp4"/></video>}<div className="hero-overlay"/><div className="hero-copy"><p className="public-eyebrow">Odontología integral · Atención cercana</p><h1 id="hero-title">Tu sonrisa merece un cuidado extraordinario.</h1><p>Un espacio pensado para que te sientas acompañado, seguro y en buenas manos.</p><div className="hero-actions"><button type="button" className="public-primary" onClick={()=>go('contact')}>Contactanos</button><a className="public-secondary" href={whatsappUrl} target="_blank" rel="noreferrer">Escribinos por WhatsApp</a><button type="button" className="public-secondary" aria-pressed={showVideo} onClick={()=>setShowVideo((value)=>!value)}>{showVideo?'Ver imagen':'Ver video'}</button></div></div><div className="hero-badge"><strong>Dar Sonrisas</strong><span>Tu bienestar empieza por una sonrisa sana.</span></div></section>
      <section id="nosotros" className="about-section"><div><p className="public-eyebrow">Nosotros</p><h2>Cuidado profesional, trato humano.</h2></div><div><p className="about-lead">Somos una empresa destinada al cuidado y mejoramiento de la salud bucal. Te ofrecemos tratamientos garantizados por el mejor personal odontológico.</p><button type="button" className="text-link" onClick={()=>go('contact')}>Conocé cómo podemos ayudarte →</button></div></section>
      <section className="service-section" aria-labelledby="services-title"><div className="section-intro"><p className="public-eyebrow">Una experiencia diferente</p><h2 id="services-title">Todo comienza escuchándote.</h2><p>Diseñamos cada atención alrededor de tus necesidades, con explicaciones claras y acompañamiento en cada etapa.</p></div><div className="service-grid"><article><span>01</span><h3>Evaluación integral</h3><p>Conocemos tu situación y construimos contigo el camino de cuidado más adecuado.</p></article><article><span>02</span><h3>Prevención</h3><p>Hábitos, controles y seguimiento para proteger tu salud bucal a largo plazo.</p></article><article><span>03</span><h3>Tratamiento personalizado</h3><p>Alternativas claras, presupuesto previo y una atención pensada para vos.</p></article></div></section>
      <section className="cta-section"><div><p className="public-eyebrow">Estamos para escucharte</p><h2>¿Tenés una consulta?</h2><p>Contanos qué necesitás y nuestro equipo se pondrá en contacto contigo.</p></div><div className="hero-actions"><button type="button" className="public-primary" onClick={()=>go('contact')}>Enviar una consulta</button><a className="public-secondary public-secondary--dark" href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp</a></div></section></main>:<main id="contenido-publico" className="contact-page"><section className="contact-intro"><button type="button" className="text-link" onClick={()=>go('home')}>← Volver al inicio</button><p className="public-eyebrow">Contacto</p><h1>Hablemos de tu sonrisa.</h1><p>Completá el formulario y se abrirá tu aplicación de correo con la consulta preparada.</p><div className="contact-direct"><span>Correo</span><a href="mailto:mendez.jose87@gmail.com">mendez.jose87@gmail.com</a><span>WhatsApp</span><a href={whatsappUrl} target="_blank" rel="noreferrer">+595 994 761 736</a></div></section><form className="contact-form" onSubmit={send}><label>Nombre y apellido<input name="name" autoComplete="name" required/></label><label>Correo electrónico<input name="email" type="email" autoComplete="email" required/></label><label>Teléfono<input name="phone" type="tel" autoComplete="tel" placeholder="+595…"/></label><label>Motivo<select name="subject" required defaultValue=""><option value="" disabled>Seleccioná una opción</option><option>Consulta general</option><option>Solicitar una cita</option><option>Tratamientos y presupuesto</option><option>Otra consulta</option></select></label><label className="contact-form__wide">Mensaje<textarea name="message" rows={6} maxLength={2000} required/></label><p className="contact-form__notice">No incluyas diagnósticos, estudios ni información médica sensible en este formulario.</p><button className="public-primary contact-form__submit">Preparar correo</button></form></main>}
    <footer className="public-footer"><img src="/media/dar-sonrisas-logo.png" alt="Dar Sonrisas"/><p>Odontología integral con una mirada humana.</p><div><a href={facebookUrl} target="_blank" rel="noreferrer">Facebook</a><a href={instagramUrl} target="_blank" rel="noreferrer">Instagram</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp</a></div><small>© {new Date().getFullYear()} Dar Sonrisas.</small></footer></div>;
}
