import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { StaffRole, StaffUser } from './types';

const roleLabels:Record<StaffRole,string>={admin:'Administración',profesional:'Profesional',recepcion:'Recepción'};

export function StaffUsers({currentUserId}:{currentUserId:string}){
  const [items,setItems]=useState<StaffUser[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [resetting,setResetting]=useState<StaffUser|null>(null);
  async function load(){try{setItems(await api.staffUsers());}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cargar los usuarios.');}}
  useEffect(()=>{void load();},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{await api.createStaffUser({email:String(data.get('email')).trim(),display_name:String(data.get('display_name')).trim(),password:String(data.get('password')),role:String(data.get('role')) as StaffRole});form.reset();await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible crear el usuario.');}finally{setBusy(false);}}
  async function toggle(item:StaffUser){setBusy(true);setError('');try{const updated=await api.updateStaffUser(item.id,{active:!item.active});setItems((current)=>current.map((value)=>value.id===item.id?updated:value));}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible actualizar el acceso.');}finally{setBusy(false);}}
  async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!resetting)return;setBusy(true);setError('');const password=String(new FormData(event.currentTarget).get('password'));try{await api.resetStaffPassword(resetting.id,password);setResetting(null);}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cambiar la contraseña.');}finally{setBusy(false);}}
  return <section aria-labelledby="users-title"><div className="section-heading"><div><p className="eyebrow">Seguridad</p><h1 id="users-title">Usuarios del personal</h1></div><span>{items.filter((item)=>item.active).length} activos</span></div>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <form className="card form-grid" onSubmit={create}><h2>Crear acceso</h2><label>Nombre visible<input name="display_name" maxLength={100} required/></label><label>Correo<input name="email" type="email" autoComplete="off" required/></label><label>Rol<select name="role" defaultValue="recepcion"><option value="recepcion">Recepción</option><option value="profesional">Profesional</option><option value="admin">Administración</option></select></label><label>Contraseña temporal<input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><button disabled={busy}>Crear usuario</button></form>
    {resetting&&<form className="card form-grid" onSubmit={resetPassword}><h2>Nueva contraseña para {resetting.display_name}</h2><label>Contraseña temporal<input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><button disabled={busy}>Cambiar contraseña</button><button type="button" className="button-secondary" onClick={()=>setResetting(null)}>Cancelar</button></form>}
    <div className="card table-wrap"><table><caption>Cuentas internas</caption><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><th scope="row">{item.display_name}</th><td>{item.email}</td><td>{roleLabels[item.role]}</td><td>{item.active?'Activo':'Inactivo'}</td><td><div className="table-actions"><button type="button" className="button-secondary" onClick={()=>setResetting(item)}>Contraseña</button><button type="button" className="button-secondary" disabled={busy||item.id===currentUserId} onClick={()=>void toggle(item)}>{item.active?'Desactivar':'Reactivar'}</button></div></td></tr>)}</tbody></table></div>
  </section>;
}
