import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { OdontogramWorkItem, ToothSurface, TreatmentPlan, TreatmentPlanStatus } from './types';

export const planStatusLabels:Record<TreatmentPlanStatus,string>={draft:'Borrador',proposed:'Propuesto',accepted:'Aceptado',rejected:'Rechazado',in_progress:'En curso',completed:'Completado',cancelled:'Cancelado'};
const transitions:Partial<Record<TreatmentPlanStatus,{status:TreatmentPlanStatus;label:string}[]>>={draft:[{status:'proposed',label:'Presentar presupuesto'},{status:'cancelled',label:'Cancelar'}],proposed:[{status:'accepted',label:'Registrar aceptación'},{status:'rejected',label:'Registrar rechazo'},{status:'cancelled',label:'Cancelar'}],accepted:[{status:'in_progress',label:'Iniciar tratamiento'},{status:'cancelled',label:'Cancelar'}],in_progress:[{status:'completed',label:'Completar'},{status:'cancelled',label:'Cancelar'}]};
const money=(value:string)=>new Intl.NumberFormat('es-PY',{style:'currency',currency:'PYG',maximumFractionDigits:0}).format(Number(value));
const surfaceLabels:Record<ToothSurface,string>={whole:'Pieza completa',mesial:'Mesial',distal:'Distal',buccal:'Vestibular',lingual:'Lingual/palatina',occlusal:'Oclusal',incisal:'Incisal'};

export function TreatmentPlans({patientId}:{patientId:string}){
  const [plans,setPlans]=useState<TreatmentPlan[]>([]);const [workItems,setWorkItems]=useState<OdontogramWorkItem[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.treatmentPlans(patientId),api.odontogramWorkItems(patientId)]).then(([p,w])=>{setPlans(p);setWorkItems(w);}).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar los planes de tratamiento.'));
  useEffect(()=>{load();},[patientId]);
  const available=workItems.filter((item)=>!item.completed_at&&!item.current_plan_id);
  async function create(){setBusy(true);setError('');try{await api.createTreatmentPlan(patientId,{title:`Presupuesto odontograma ${plans.length+1}`,clinical_notes:null,valid_until:null,from_odontogram:true});await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible crear el presupuesto.');}finally{setBusy(false);}}
  async function importWork(planId:string){setBusy(true);setError('');try{await api.importOdontogramIntoPlan(patientId,planId);await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cargar los trabajos.');}finally{setBusy(false);}}
  async function changePrice(event:FormEvent<HTMLFormElement>,planId:string,itemId:string){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{await api.changePlanItemPrice(patientId,planId,itemId,String(data.get('unit_price')));await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible actualizar el precio.');}finally{setBusy(false);}}
  async function changeStatus(plan:TreatmentPlan,status:TreatmentPlanStatus){setBusy(true);setError('');try{await api.changeTreatmentPlanStatus(patientId,plan.id,status);await load();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cambiar el estado.');}finally{setBusy(false);}}
  return <section className="card" aria-labelledby="plans-title"><h2 id="plans-title">Planes de tratamiento y presupuestos</h2><p>Los importes son presupuestos de referencia en guaraníes; no constituyen una factura.</p>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <section aria-labelledby="budget-work-title"><h3 id="budget-work-title">Trabajos activos disponibles ({available.length})</h3>{available.length?<><p>Estos trabajos vienen del Odontograma. Podés crear un presupuesto con todos ellos.</p><ul className="work-list">{available.map((item)=><li key={item.id}><strong>Pieza {item.tooth_code} · {surfaceLabels[item.surface]} · {item.treatment_name}</strong><span>Activo · sin presupuesto</span></li>)}</ul><button type="button" disabled={busy} onClick={()=>void create()}>Crear presupuesto con {available.length} trabajo{available.length===1?'':'s'}</button></>:<p>Registrá primero los trabajos propuestos en Odontograma.</p>}</section>
    {plans.length?plans.map((plan)=><article className="clinical-entry" key={plan.id}><h3>{plan.title}</h3><p><strong>Estado:</strong> {planStatusLabels[plan.status]} · <strong>Total:</strong> {money(plan.total)}</p>{plan.valid_until&&<p>Válido hasta: {new Intl.DateTimeFormat('es-PY').format(new Date(`${plan.valid_until}T12:00:00`))}</p>}{plan.clinical_notes&&<p>{plan.clinical_notes}</p>}
      {plan.items.length?<ul className="work-list">{plan.items.map((item)=><li key={item.id}><strong>{item.quantity} × {item.treatment_code} — {item.description}{item.tooth_code?` · pieza ${item.tooth_code}`:''}{item.work_item_id?` · ${surfaceLabels[workItems.find((work)=>work.id===item.work_item_id)?.surface??'whole']}`:''}</strong><span>{money(item.subtotal)}{item.work_item_id?` · ${workItems.find((work)=>work.id===item.work_item_id)?.completed_at?'Finalizado':'Activo'}`:''}</span>{plan.status==='draft'&&<form className="budget-price-form" onSubmit={(event)=>void changePrice(event,plan.id,item.id)}><label>Precio unitario (Gs.)<input name="unit_price" type="number" min="0" step="1" defaultValue={item.unit_price} required/></label><button className="button-secondary" disabled={busy}>Actualizar precio</button></form>}</li>)}</ul>:<p>Sin tratamientos agregados.</p>}
      {plan.status==='draft'&&available.length>0&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>void importWork(plan.id)}>Cargar {available.length} trabajo{available.length===1?'':'s'} del odontograma</button>}
      <div className="actions">{(transitions[plan.status]??[]).filter((item)=>item.status!=='completed'||!plan.items.some((entry)=>entry.work_item_id)).map((item)=><button type="button" className="button-secondary" disabled={busy} key={item.status} onClick={()=>changeStatus(plan,item.status)}>{item.label}</button>)}</div>
    </article>):<p>No hay planes de tratamiento.</p>}
  </section>;
}
