import { FormEvent, useEffect, useState } from 'react';
import { api, ApiError } from './api';
import type { Treatment, TreatmentPlan, TreatmentPlanStatus } from './types';

export const planStatusLabels:Record<TreatmentPlanStatus,string>={draft:'Borrador',proposed:'Propuesto',accepted:'Aceptado',rejected:'Rechazado',in_progress:'En curso',completed:'Completado',cancelled:'Cancelado'};
const transitions:Partial<Record<TreatmentPlanStatus,{status:TreatmentPlanStatus;label:string}[]>>={draft:[{status:'proposed',label:'Presentar presupuesto'},{status:'cancelled',label:'Cancelar'}],proposed:[{status:'accepted',label:'Registrar aceptación'},{status:'rejected',label:'Registrar rechazo'},{status:'cancelled',label:'Cancelar'}],accepted:[{status:'in_progress',label:'Iniciar tratamiento'},{status:'cancelled',label:'Cancelar'}],in_progress:[{status:'completed',label:'Completar'},{status:'cancelled',label:'Cancelar'}]};
const money=(value:string)=>new Intl.NumberFormat('es-PY',{style:'currency',currency:'PYG',maximumFractionDigits:0}).format(Number(value));

export function TreatmentPlans({patientId}:{patientId:string}){
  const [plans,setPlans]=useState<TreatmentPlan[]>([]);const [treatments,setTreatments]=useState<Treatment[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.treatmentPlans(patientId),api.treatments()]).then(([p,t])=>{setPlans(p);setTreatments(t);}).catch((reason)=>setError(reason instanceof ApiError?reason.message:'No fue posible cargar los planes de tratamiento.'));
  useEffect(()=>{load();},[patientId]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const plan=await api.createTreatmentPlan(patientId,{title:String(data.get('title')).trim(),clinical_notes:String(data.get('clinical_notes')).trim()||null,valid_until:String(data.get('valid_until'))||null});setPlans((items)=>[plan,...items]);form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible crear el plan.');}finally{setBusy(false);}}
  async function addItem(event:FormEvent<HTMLFormElement>,planId:string){event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const plan=await api.addTreatmentPlanItem(patientId,planId,{treatment_id:String(data.get('treatment_id')),tooth_code:String(data.get('tooth_code')).trim()||null,quantity:Number(data.get('quantity')),unit_price:String(data.get('unit_price')).trim()||null});setPlans((items)=>items.map((item)=>item.id===plan.id?plan:item));form.reset();}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible agregar el tratamiento.');}finally{setBusy(false);}}
  async function changeStatus(plan:TreatmentPlan,status:TreatmentPlanStatus){setBusy(true);setError('');try{const updated=await api.changeTreatmentPlanStatus(patientId,plan.id,status);setPlans((items)=>items.map((item)=>item.id===updated.id?updated:item));}catch(reason){setError(reason instanceof ApiError?reason.message:'No fue posible cambiar el estado.');}finally{setBusy(false);}}
  return <section className="card" aria-labelledby="plans-title"><h2 id="plans-title">Planes de tratamiento y presupuestos</h2><p>Los importes son presupuestos de referencia en guaraníes; no constituyen una factura.</p>{error&&<div className="notice notice--error" role="alert">{error}</div>}
    <form className="form-grid" onSubmit={create}><h3>Nuevo plan</h3><label>Título<input name="title" maxLength={200} required/></label><label>Válido hasta<input name="valid_until" type="date"/></label><label>Notas clínicas<textarea name="clinical_notes" maxLength={4000}/></label><button disabled={busy}>Crear borrador</button></form>
    {plans.length?plans.map((plan)=><article className="clinical-entry" key={plan.id}><h3>{plan.title}</h3><p><strong>Estado:</strong> {planStatusLabels[plan.status]} · <strong>Total:</strong> {money(plan.total)}</p>{plan.valid_until&&<p>Válido hasta: {new Intl.DateTimeFormat('es-PY').format(new Date(`${plan.valid_until}T12:00:00`))}</p>}{plan.clinical_notes&&<p>{plan.clinical_notes}</p>}
      {plan.items.length?<ul>{plan.items.map((item)=><li key={item.id}>{item.quantity} × {item.treatment_code} — {item.description}{item.tooth_code?` (pieza ${item.tooth_code})`:''}: {money(item.subtotal)}</li>)}</ul>:<p>Sin tratamientos agregados.</p>}
      {plan.status==='draft'&&<form className="form-grid" onSubmit={(event)=>addItem(event,plan.id)}><h4>Agregar tratamiento</h4><label>Tratamiento<select name="treatment_id" required defaultValue=""><option value="" disabled>Seleccione</option>{treatments.map((item)=><option value={item.id} key={item.id}>{item.code} — {item.name} ({money(item.default_price)})</option>)}</select></label><label>Pieza FDI (opcional)<input name="tooth_code" inputMode="numeric" maxLength={2}/></label><label>Cantidad<input name="quantity" type="number" min="1" max="100" defaultValue="1" required/></label><label>Precio unitario personalizado (opcional)<input name="unit_price" type="number" min="0" step="1" placeholder="Usar precio del catálogo"/></label><button disabled={busy||!treatments.length}>Agregar al presupuesto</button></form>}
      <div className="actions">{(transitions[plan.status]??[]).map((item)=><button type="button" className="button-secondary" disabled={busy} key={item.status} onClick={()=>changeStatus(plan,item.status)}>{item.label}</button>)}</div>
    </article>):<p>No hay planes de tratamiento.</p>}
  </section>;
}
