export type StaffRole = 'admin' | 'profesional' | 'recepcion';
export type AuthenticatedUser = { id: string; display_name: string; email: string; roles: StaffRole[] };
export type LoginResponse = { user: AuthenticatedUser; csrf_token: string };

export type Patient = {
  id: string;
  first_name: string;
  last_name: string;
  document_type: string;
  document_number: string;
  birth_date?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  occupation?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  active: boolean;
  created_at: string;
};
export type PatientInput = Omit<Patient, 'id'|'active'|'created_at'>;
export type PatientUpdate = Omit<PatientInput,'document_type'|'document_number'> & {active?:boolean};

export type Professional = { id: string; display_name: string; specialty: string; active: boolean; created_at: string };
export type ProfessionalInput = Pick<Professional, 'display_name'|'specialty'>;
export type ProfessionalUpdate = Partial<Pick<Professional, 'display_name'|'specialty'|'active'>>;

export type Appointment = {
  id: string;
  patient_id: string;
  professional_id: string;
  starts_at: string;
  ends_at: string;
  reason?: string | null;
  status: 'scheduled'|'cancelled'|'completed';
  created_at: string;
};
export type AppointmentInput = Omit<Appointment, 'id'|'status'|'created_at'>;
export type StaffUser = {id:string;email:string;display_name:string;role:StaffRole;active:boolean};
export type StaffUserInput = {email:string;display_name:string;password:string;role:Exclude<StaffRole,'paciente'>};
export type AuditEvent = {id:string;actor_id:string;action:string;resource_type:string;resource_id?:string|null;outcome:string;occurred_at:string};

export type ClinicalProfile = {
  id: string;
  patient_id: string;
  blood_type?: string | null;
  allergies: string[];
  medications: string[];
  medical_conditions: string[];
  observations?: string | null;
  updated_at: string;
  updated_by: string;
};
export type ClinicalProfileInput = Pick<ClinicalProfile, 'blood_type'|'allergies'|'medications'|'medical_conditions'|'observations'>;
export type ClinicalEntry = { id:string; patient_id:string; author_id:string; entry_type:'consultation'|'evolution'|'diagnosis'|'procedure'; occurred_at:string; summary:string; notes:string; created_at:string };
export type ClinicalEntryInput = Pick<ClinicalEntry,'entry_type'|'occurred_at'|'summary'|'notes'>;
export type ConsentRecord = { id:string; patient_id:string; consent_type:string; document_version:string; purpose:string; signed_at:string; signer_name:string; signer_relationship?:string|null; evidence_location:string; status:'active'|'revoked'; revoked_at?:string|null; created_at:string };
export type ConsentInput = Pick<ConsentRecord,'consent_type'|'document_version'|'purpose'|'signed_at'|'signer_name'|'signer_relationship'|'evidence_location'>;
export type DentalCondition = 'healthy'|'caries'|'missing'|'restoration'|'crown'|'implant'|'root_canal'|'extraction_indicated';
export type ToothSurface = 'whole'|'mesial'|'distal'|'buccal'|'lingual'|'occlusal'|'incisal';
export type OdontogramEvent = {id:string;patient_id:string;recorded_by:string;tooth_code:string;surface:ToothSurface;condition:DentalCondition;observed_at:string;note?:string|null;treatment_id?:string|null;created_at:string};
export type OdontogramEventInput = Pick<OdontogramEvent,'tooth_code'|'surface'|'condition'|'observed_at'|'note'|'treatment_id'>;
export type Treatment = {id:string;code:string;name:string;category:string;default_price:string;currency:'PYG';active:boolean;created_at:string};
export type TreatmentInput = Pick<Treatment,'code'|'name'|'category'|'default_price'>;
export type TreatmentPlanStatus = 'draft'|'proposed'|'accepted'|'rejected'|'in_progress'|'completed'|'cancelled';
export type TreatmentPlanItem = {id:string;treatment_id:string;tooth_code?:string|null;treatment_code:string;description:string;quantity:number;unit_price:string;currency:'PYG';subtotal:string};
export type TreatmentPlan = {id:string;patient_id:string;created_by:string;title:string;clinical_notes?:string|null;status:TreatmentPlanStatus;valid_until?:string|null;accepted_at?:string|null;created_at:string;items:TreatmentPlanItem[];total:string};
export type TreatmentPlanInput = Pick<TreatmentPlan,'title'|'clinical_notes'|'valid_until'>;
export type TreatmentPlanItemInput = {treatment_id:string;tooth_code?:string|null;quantity:number;unit_price?:string|null};
export type InvoiceStatus = 'issued'|'partially_paid'|'paid'|'cancelled';
export type PaymentMethod = 'cash'|'card'|'transfer'|'other';
export type Payment = {id:string;amount:string;method:PaymentMethod;paid_at:string;reference?:string|null;created_at:string};
export type Invoice = {id:string;patient_id:string;treatment_plan_id:string;number:string;description:string;amount:string;currency:'PYG';due_date?:string|null;status:InvoiceStatus;cancelled_at?:string|null;created_at:string;payments:Payment[];paid_amount:string;balance:string};
export type BillablePlan = {id:string;title:string;total:string};
export type PaymentInput = {amount:string;method:PaymentMethod;paid_at:string;reference?:string|null};
export type ReportSummary = {from_date:string;to_date:string;active_patients:number;appointments_in_range:number;upcoming_appointments:number;collected_amount:string;outstanding_balance:string;invoices_by_status:Record<InvoiceStatus,number>;currency:'PYG'};
export type NotificationChannel = 'whatsapp'|'sms';
export type NotificationConsentStatus = 'granted'|'revoked';
export type NotificationDeliveryStatus = 'pending'|'sent'|'failed'|'cancelled';
export type NotificationConsent = {id:string;patient_id:string;channel:NotificationChannel;status:NotificationConsentStatus;granted_at:string;revoked_at?:string|null;evidence_location:string;created_at:string};
export type PatientNotification = {id:string;patient_id:string;appointment_id?:string|null;channel:NotificationChannel;recipient:string;template_key?:string|null;message:string;status:NotificationDeliveryStatus;processed_at?:string|null;cancelled_at?:string|null;provider_reference?:string|null;failure_code?:string|null;created_at:string};
